server:
  port: 8500


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka


spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: auth-server
          uri: lb://MY-AUTH-SERVER
          predicates:
            - Path=/auth-server/**
          filters:
            - RewritePath=/auth-server/(?<segment>.*), /$\{segment}

        - id: theater-server
          uri: lb://MY-MOVIE-THEATER-SERVICE
          predicates:
            - Path=/theater-server/**
          filters:
            - RewritePath=/theater-server/(?<segment>.*), /$\{segment}

        - id: cinema-server
          uri: lb://MY-CINEMA-SERVER
          predicates:
            - Path=/cinema-server/**
          filters:
            - RewritePath=/cinema-server/(?<segment>.*), /$\{segment}

        - id: info-server
          uri: lb://MY-MOVIE-INFORMATION-SERVER
          predicates:
            - Path=/info-server/**
          filters:
            - RewritePath=/info-server/(?<segment>.*), /$\{segment}

        - id: user-server
          uri: lb://MY-USER-SERVICE
          predicates:
            - Path=/user-server/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-server/(?<segment>.*), /$\{segment}
            - GlobalFilter

        - id: movie-server
          uri: lb://MY-MOVIE-SERVICE
          predicates:
            - Path=/movie-server/**
          filters:
            - RewritePath=/movie-server/(?<segment>.*), /$\{segment}
        - id: movie-comment-server
          uri: lb://MY-MOVIE-COMMENT-SERVICE
          predicates:
            - Path=/movie-comment-server/**
          filters:
            - RewritePath=/movie-comment-server/(?<segment>.*), /$\{segment}
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWJqLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbAo=GzcMAY5
  token-validity-in-seconds: 1000000




