server:
  port: 8760
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: auth-server
          uri: lb://MY-AUTH-SERVER
          predicates:
            - Path=/auth-server/**
          filters:
            - RewritePath=/auth-server/(?<segment>.*), /$\{segment}

        - id: user-server
          uri: lb://MY-USER-SERVICE
          predicates:
            - Path=/user-server/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-server/(?<segment>.*), /$\{segment}
            - GlobalFilter
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWJqLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbAo=GzcMAY5
  token-validity-in-seconds: 1000000




