server:
  port: 8760

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigureations:
          '[/**]':
            alowedOrigins: "http://localhost:8333"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
        default-filters:
          - DedupeResponseHeader=Access-control-Allow-Orign Access-Control-Allow-Credentials
      routes:
        - id: auth-server
          uri: lb://MY-AUTH-SERVER
          predicates:
            - Path=/auth-server/**
          filters:
            - RewritePath=/auth-server/(?<segment>.*), /$\{segment}
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWJqLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbAo=GzcMAY5
  token-validity-in-seconds: 1000000




